# Generated by Django 5.1.1 on 2024-09-11 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_moodentry_id_alter_moodentry_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(max_length=255),
        ),
    ]
